pipeline {
    agent any

    environment {
        DB_CONTAINER_NAME = 'jenkins-mariadb'
        DB_ROOT_PASSWORD = 'rootpass'
        DB_PORT = '3307'
    }

    stages {
        stage('Clean Up Old DB Container') {
            steps {
                sh 'docker rm -f $DB_CONTAINER_NAME || true'
            }
        }

        stage('Start MariaDB Container') {
            steps {
                sh '''
                docker run -d --name $DB_CONTAINER_NAME \
                    -e MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD \
                    -e MYSQL_DATABASE=studyroom \
                    -p $DB_PORT:3306 \
                    mariadb:10.5
                '''
                // DB가 뜰 때까지 대기
                sleep 20
            }
        }

        stage('Clone Backend') {
            steps {
                git url: 'https://github.com/yourname/studyroom-backend.git', branch: 'main'
            }
        }

        stage('Build with Maven') {
            steps {
                dir('backend') {
                    sh './mvnw clean package'
                }
            }
        }

        stage('Remove DB Container') {
            steps {
                sh 'docker rm -f $DB_CONTAINER_NAME'
            }
        }
    }
}
